<hr>
<footer>
        <div class="row-fluid">
            <div class="span4">
			  <div class="fb-like" data-href="http://www.facebook.com/leaplibras" data-layout="standard" data-action="like" data-show-faces="true" data-share="true">
              </div>
            </div>
            <div class="span4 offset4 text-right">
              <p>©2013 Leap-LIBRAS &nbsp; &nbsp; &nbsp;<a href='?controle=Termo&acao=listarTermo'>Termos de uso</a></p>
            </div>
        </div>
</footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./template/bootstrap/js/jquery.js"></script>
    <script src="./template/bootstrap/js/bootstrap.js"></script>


	<script src="./trainerv03/trainer-ui/js/jquery.touchwipe.min.js"></script>

	<script src="./trainerv03/trainer-ui/js/three.min.js"></script>
	<script src="./trainerv03/trainer-ui/js/detector.js"></script>
	<script src="./trainerv03/trainer-ui/js/tween.js"></script>
	<script src="./trainerv03/trainer-ui/js/orbit-controls.js"></script>

	<!-- A local copy of the Leap Motion Javascript API is useful during testing-->
	<script src="./trainerv03/lib/leap.js"></script>
	<!-- script src="http://js.leapmotion.com/0.2.0/leap.min.js"></script -->
		
	<script src="./trainerv03/leaptrainer.js"></script>
	
	<script src="./trainerv03/sub-classes/high-resolution-recording.js"></script>
	<script src="./trainerv03/sub-classes/lib/brain.js"></script>
	<script src="./trainerv03/sub-classes/neural-networks.js"></script>
	<script src="./trainerv03/sub-classes/cross-correlation.js"></script>
	
	<script src="./template/js/leaplibras-ui.js"></script>
	<script>
	$(function() {
		
		if($('#gestoJSON').val()!="")
		{					
			
			var trainer = new LeapTrainer.Controller();		
			
			trainer.fromJSON($('#gestoJSON').val());
			
			trainer.on('gesture-recognized', function (hit, gestureName) {	    
			
			
				$('#mensagem_usuario').text('Gesto realizado com sucesso!!!');
				
				
				$('#proximo_gesto').toggleClass( 'disabled', false );
				
			});
		
		}
		
	});
	
	</script>


  
