<footer>
        <div class="row-fluid">
            <div class="span4">
              <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-layout="standard" data-action="like" data-show-faces="false" data-send="false">
              </div>
            </div>
            <div class="span4 offset4 text-right">
              <p>©2013 Leap-LIBRAS &nbsp; &nbsp; &nbsp;<a href="#">Termos de uso</a></p>
            </div>
        </div>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./template/bootstrap/js/jquery.js"></script>
    <script src="./template/bootstrap/js/bootstrap.js"></script>


  
