<hr>
<footer>
        <div class="row-fluid">
            <div class="span4">
              <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-layout="standard" data-action="like" data-show-faces="false" data-send="false">
              </div>
            </div>
            <div class="span4 offset4 text-right">
              <p>©2013 Leap-LIBRAS &nbsp; &nbsp; &nbsp;<a href='?controle=Termo&acao=listarTermo'>Termos de uso</a></p>
            </div>
        </div>
</footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./template/bootstrap/js/jquery.js"></script>
    <script src="./template/bootstrap/js/bootstrap.js"></script>


	<script src="./trainer/trainer-ui/js/jquery.touchwipe.min.js"></script>

	<script src="./trainer/trainer-ui/js/three.min.js"></script>
	<script src="./trainer/trainer-ui/js/detector.js"></script>
	<script src="./trainer/trainer-ui/js/tween.js"></script>
	<script src="./trainer/trainer-ui/js/orbit-controls.js"></script>

	<!-- A local copy of the Leap Motion Javascript API is useful during testing-->
	<script src="./trainer/lib/leap.js"></script>
	<!-- script src="http://js.leapmotion.com/0.2.0/leap.min.js"></script -->
		
	<script src="./trainer/leaptrainer.js"></script>
	
	<script src="./trainer/sub-classes/high-resolution-recording.js"></script>
	<script src="./trainer/sub-classes/lib/brain.js"></script>
	<script src="./trainer/sub-classes/neural-networks.js"></script>
	<script src="./trainer/sub-classes/cross-correlation.js"></script>
	
	<script src="./template/js/leaplibras-ui.js"></script>


  
