<!DOCTYPE html>
<!-- saved from url=(0048)http://getbootstrap.com/2.3.2/examples/hero.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Leap-LIBRAS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->

    <link href="template/css/leaplibras-ui.css" rel="stylesheet">

    <link href="template/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="template/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

  </head>

  <body>
  <div id="fb-root"></div>
  <script>  
  	window.fbAsyncInit = function() {
	    FB.init({
	      appId      : '540608949358823',
	      status     : true, // check login status
	      cookie     : true, // enable cookies to allow the server to access the session
	      xfbml      : true,  // parse XFBML
		  oauth		 : true
	    });

        FB.Event.subscribe('auth.login', function(response) {
		  console.log('login');
          window.location.reload();
        });
        FB.Event.subscribe('auth.logout', function(response) {
		  console.log('logout');
          window.location.href = 'https://leaplibras.herokuapp.com';
        });
    };

	// Load the SDK's source Asynchronously
	  // Note that the debug version is being actively developed and might 
	  // contain some type checks that are overly strict. 
	  // Please report such bugs using the bugs tool.
	  (function(d, debug){
	     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
	     if (d.getElementById(id)) {return;}
	     js = d.createElement('script'); js.id = id; js.async = true;
	     js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
	     ref.parentNode.insertBefore(js, ref);
	   }(document, /*debug*/ false));
  </script>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href='?controle=Home&acao=listarHome'>Leap-LIBRAS</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
				<!-- <?php if(isset($_SESSION['nome_usuario'])) { ?>
					<li class="active">
						<span class="brand"><?php echo "Olá, " . $_SESSION['nome_usuario']; ?></span>
					</li>
				<?php } ?> -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sobre Nós <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href='?controle=Equipe&acao=listarEquipe'>Equipe</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Disciplina&acao=listarDisciplina'>Disciplina</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Contact&acao=listarContact'>Contato</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">O Jogo <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href='?controle=Explicacao&acao=listarExplicacao'>Explicação</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=LIBRAS&acao=listarLIBRAS'>LIBRAS</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Media&acao=listarMedia'>Vídeo-aulas</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Jogar <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="nav-header">níveis do jogo</li>
				  <?php
			  		$o_nivel = new NivelModel();
			  		$v_niveis = $o_nivel->_list();
				  	for($i = 0; $i < count($v_niveis); $i++) {
						$o_nivel = $v_niveis[$i];
						$classe_li = "";
						$classe_a = "";
						$level = (int)$o_nivel->getLevel();
						$titulo_nivel = $o_nivel->getNome();
						
						if((int)$_SESSION['level_usuario'] < $level) {
							$classe_li = "disabled";
							$classe_a = "disabled_link";
						}
						
						if ($i > 0)
							echo "<li class='divider'></li>";
						echo "<li class='$classe_li'><a href='?controle=Jogo&acao=listarJogo&level=$level' class='$classe_a'>
							      $titulo_nivel
							  </a></li>";
					} 
				  ?>
                </ul>
              </li>
			  <?php
			  	if(isset($_SESSION['id_usuario']) && ((int)$_SESSION['id_usuario']) > 0) {
					$usuario_model = new UsuarioModel();
					$nivel_acesso = $usuario_model->loadById((int)$_SESSION['id_usuario'])->getNivelAcesso();
					if ($nivel_acesso->getAdminAcessos() || $nivel_acesso->getAdminGestos()) {
			  ?>
	              <li class="dropdown">
	                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gerenciar <b class="caret"></b></a>
	                <ul class="dropdown-menu">
						<?php if ($nivel_acesso->getAdminGestos()) { ?>
	                  		<li><a target="_blank" href='?controle=MidiaGesto&acao=leapTrainerIndex'>Gestos</a></li>
						<?php } ?>
						<?php if ($nivel_acesso->getAdminGestos() && $nivel_acesso->getAdminAcessos()) { ?>
							<li class="divider"></li>
						<?php } ?>
						<?php if ($nivel_acesso->getAdminAcessos()) { ?>
	                  		<li><a href='?controle=Usuario&acao=listarUsuario'>Acessos dos Usuários</a></li>
	                  	    <li class="divider"></li>
	                  	    <li><a href='?controle=Tabela&acao=listarTabela'>Tabelas</a></li>
						<?php } ?>
	                </ul>
	              </li>
			  <?php
		  			}
				}
			  ?>
            </ul>
            <form class="navbar-form pull-right">
				<fb:login-button show-faces="true" scope="email,user_birthday" />
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">