<!DOCTYPE html>
<!-- saved from url=(0048)http://getbootstrap.com/2.3.2/examples/hero.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Leap-LIBRAS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="http://getbootstrap.com/2.3.2/assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="http://getbootstrap.com/2.3.2/assets/ico/favicon.png">
  <style type="text/css"></style></head>

  <body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="brand">Leap-LIBRAS</div>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="dropdown">
                <a href="http://getbootstrap.com/2.3.2/examples/hero.html#" class="dropdown-toggle" data-toggle="dropdown">Sobre Nós <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Equipe</a></li>
                  <li class="divider"></li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Disciplina</a></li>
                  <li class="divider"></li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Contato</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="http://getbootstrap.com/2.3.2/examples/hero.html#" class="dropdown-toggle" data-toggle="dropdown">O Jogo <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Explicação</a></li>
                  <li class="divider"></li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">LIBRAS</a></li>
                  <li class="divider"></li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Vídeo-aulas</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="http://getbootstrap.com/2.3.2/examples/hero.html#" class="dropdown-toggle" data-toggle="dropdown">Jogar <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="nav-header">níveis do jogo</li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Nível 1</a></li>
                  <li class="divider"></li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Nível 2</i></a></li>
                  <li class="divider"></li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Nível 3</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="http://getbootstrap.com/2.3.2/examples/hero.html#" class="dropdown-toggle" data-toggle="dropdown">Gerenciar <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Gestos</a></li>
                  <li class="divider"></li>
                  <li><a href="http://getbootstrap.com/2.3.2/examples/hero.html#">Acessos</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Log in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">