<!DOCTYPE html>
<!-- saved from url=(0048)http://getbootstrap.com/2.3.2/examples/hero.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Leap-LIBRAS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->

    <link href="template/css/leaplibras-ui.css" rel="stylesheet">

    <link href="template/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="template/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

  </head>

  <body>
  <div id="fb-root"></div>
  <script>
    window.fbAsyncInit = function() {
		FB.init({
		  appId      : '540608949358823',
		  status     : true, // check login status
		  cookie     : true, // enable cookies to allow the server to access the session
		  xfbml      : true  // parse XFBML
		});

		// Here we subscribe to the auth.authResponseChange JavaScript event. This event is fired
		// for any authentication related change, such as login, logout or session refresh. This means that
		// whenever someone who was previously logged out tries to log in again, the correct case below 
		// will be handled. 
		FB.Event.subscribe('auth.authResponseChange', function(response) {
		  // Here we specify what we do with the response anytime this event occurs. 
		  if (response.status === 'connected') {
		    // The response object is returned with a status field that lets the app know the current
		    // login status of the person. In this case, we're handling the situation where they 
		    // have logged in to the app.
		    testAPI();
		  } else if (response.status === 'not_authorized') {
		    // In this case, the person is logged into Facebook, but not into the app, so we call
		    // FB.login() to prompt them to do so. 
		    // In real-life usage, you wouldn't want to immediately prompt someone to login 
		    // like this, for two reasons:
		    // (1) JavaScript created popup windows are blocked by most browsers unless they 
		    // result from direct interaction from people using the app (such as a mouse click)
		    // (2) it is a bad experience to be continually prompted to login upon page load.
		    FB.login();
		  } else {
		    // In this case, the person is not logged into Facebook, so we call the login() 
		    // function to prompt them to do so. Note that at this stage there is no indication
		    // of whether they are logged into the app. If they aren't then they'll see the Login
		    // dialog right after they log in to Facebook. 
		    // The same caveats as above apply to the FB.login() call here.
		    FB.login();
		  }
		});
	};

  	// Load the SDK asynchronously
	(function(d, s, id) {  
	  var js, fjs = d.getElementsByTagName(s)[0];
	    if (d.getElementById(id)) return;
	    js = d.createElement(s); js.id = id;
	    js.src = "//connect.facebook.net/pt_BR/all.js";
	    fjs.parentNode.insertBefore(js, fjs);
	  }(document, 'script', 'facebook-jssdk')
    );

	// Here we run a very simple test of the Graph API after login is successful. 
	// This testAPI() function is only called in those cases. 
	function testAPI() {
	  console.log('Welcome!  Fetching your information.... ');
	  FB.api('/me', function(response) {
	    console.log(response);
	  });
	}
  </script>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href='?controle=Home&acao=listarHome'>Leap-LIBRAS</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <!-- <?php
                if(isset($_SESSION['usuario'])){
                  ?>
                  <li class="active"><span class="brand">
                  <?php
                  echo "Olá, ";
                  echo $_SESSION['usuario'];
                  ?>
                  </span></li>
                  <?php
                }
              ?> -->
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sobre Nós <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href='?controle=Equipe&acao=listarEquipe'>Equipe</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Disciplina&acao=listarDisciplina'>Disciplina</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Contact&acao=listarContact'>Contato</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">O Jogo <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href='?controle=Explicacao&acao=listarExplicacao'>Explicação</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=LIBRAS&acao=listarLIBRAS'>LIBRAS</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Media&acao=listarMedia'>Vídeo-aulas</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Jogar <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="nav-header">níveis do jogo</li>
                  <li><a href='?controle=Jogo&acao=listarJogo&level=1'>Nível 1 </a></li>
                  <li class="divider"></li>
                  <li <?php if($_SESSION['levelusuario'] < 2) print "class='disabled'"; ?> ><a href='?controle=Jogo&acao=listarJogo&level=2' >Nível 2</a></li>
                  <li class="divider"></li>
                  <li <?php if($_SESSION['levelusuario'] < 3) print "class='disabled'"; ?> ><a href='?controle=Jogo&acao=listarJogo&level=3' >Nível 3</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gerenciar <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a target="_blank" href='?controle=MidiaGesto&acao=leapTrainerIndex'>Gestos</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Usuario&acao=listarUsuario'>Acessos dos Usuários</a></li>
                  <li class="divider"></li>
                  <li><a href='?controle=Tabela&acao=listarTabela'>Tabelas</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
            	<fb:login-button show-faces="true"></fb:login-button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">