<!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Contato</h1>
        <hr>
        <p>Para nos contactar, é muito fácil! </p>
        <p>Utilize um dos meios disponíveis abaixo:</p>
        <div class="row-fluid">
          <div class="span6">
            <img src="template/images/cirquinho.jpg" class="img-polaroid">
          </div>
          <div class="span6">
            <address>
            <h4><strong><a href="http://www.poli.usp.br/">Escola Politécnica da USP</a></strong></h4>
            <hr>
            <div class="row-fluid">
              <div class="span12">
                <h4>Endereço</h4>
                Av. Prof. Luciano Gualberto, travessa 3 nº 380<br>
                CEP: 05508-010<br>São Paulo - SP<br>
                <h4>Telefone</h4>
                <abbr title="Phone">P:</abbr> (11) 3091-5281
              </div>
            </div>
            <address>
          </div>
        </div>
      </div>