<!-- Main hero unit for a primary marketing message or call to action -->
<?php
  $tipoMidia = 'I';
  $imagemUrl = "upload/";
  $urlMidia = "//www.youtube.com/embed/0jl-RIwoYh8";
?>
	  <div class="hero-unit">
        <h1>Nível <?php echo $_SESSION['level']; ?></h1>
        <h2>Questão: Faça o gesto <?php echo 'X'?></h2>
        
        <hr>

        
          <div class="row-fluid">
            <?php if($_SESSION['level'] == 1){?>
            <div class="span4 text-left">
              
              <!-- Button to trigger modal -->
              <a href="#modalVideo" role="button" class="btn btn-primary btn-large" data-toggle="modal">Aprenda o gesto <i class="icon-facetime-video icon-white"></i></a>
              <!-- Modal -->
              <div id="modalVideo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalVideoLabel" aria-hidden="true">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                  <h3 id="modalVideoLabel">Aprenda o gesto <?php echo "$imagemUrl com "; if($tipoMidia =='V') echo "o vídeo."; else echo "a imagem." ?> </h3>
                </div>
                <div class="modal-body">
                  <?php 
                    if($tipoMidia =='V') 
                      echo "<iframe width='520' height='315' src='$urlMidia' frameborder='0' allowfullscreen></iframe>";
                    else{ ?>
                      <div class="row-fluid">
                        <div class="span6 offset3">
                          <?php echo "<img src='$imagemUrl$urlMidia' class='img-polaroid'>"; ?>
                        </div>
                      </div>   
                  <?php } ?>
                </div>
                <div class="modal-footer">
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                </div>
              </div>
            </div>
            <?php } else{ ?>
              <div class="span4 text-left">
                <p class="btn-primary btn-large">Aprenda o gesto <i class="icon-facetime-video icon-white"></i></p>
              </div>
            <?php } ?>


            <div class="span4 text-center">
              <p class="btn-info btn-large">Pontuação: <?php echo '10%' ?></p>
            </div>

            <div class="span4 text-right">
              <a href="#" class="btn btn-primary btn-large">Próximo gesto <i class="icon-forward icon-white"></i></a>
            </div>

          </div>
          
          <hr>
		  <div id="main">
		  	<div id="render-area"></div>
		  </div>
      </div>

        