<?php
$v_params = $this->getParams();
$v_acessos = $v_params['v_acessos'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Lista de acessos
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th>
					ID
				</th>
				<th>
					Nome
				</th>
				<th>
					Descrição
				</th>
				<th>
					Admin Gestos?
				</th>
				<th>
					Admin Acessos?
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<?php
			foreach($v_acessos AS $o_acesso)
			{
				?>
				<tr>
					<td>
						<?php echo $o_acesso->getId()?>
					</td>
					<td>
						<?php echo $o_acesso->getNome()?>
					</td>
					<td>
						<?php echo $o_acesso->getDescricao()?>
					</td>
					<td>
						<?php echo $o_acesso->getAdminGestos()?"Sim":"Não" ?>
					</td>
					<td>
						<?php echo $o_acesso->getAdminAcessos()?"Sim":"Não" ?>
					</td>
			
					<td align="center">
						<a href='?controle=Acesso&acao=manterAcesso&in_id=<?php echo $o_acesso->getId()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=Acesso&acao=apagarAcesso&in_id=<?php echo $o_acesso->getId()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
		<a href='?controle=Acesso&acao=manterAcesso' class='bt_green'>Novo Acesso</a>
	</div>
</body>
</html>