<?php
$v_params = $this->getParams();
$v_niveis = $v_params['v_niveis'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Lista de niveis
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th>
					ID
				</th>
				<th>
					Nome
				</th>
				<th>
					Id_anterior
				</th>
				<th>
					Id_proximo
				</th>
				<th>
					Level
				</th>
				<th>
					Aleatório?
				</th>
				<th>
					Total Questões
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<?php
			foreach($v_niveis AS $o_nivel)
			{
				?>
				<tr>
					<td>
						<?php echo $o_nivel->getId()?>
					</td>
					<td>
						<?php echo $o_nivel->getNome()?>
					</td>
					<td>
						<?php echo $o_nivel->getIdAnterior()?>
					</td>
					<td>
						<?php echo $o_nivel->getIdProximo()?>
					</td>
					<td>
						<?php echo $o_nivel->getLevel()?>
					</td>
					<td>
						<?php echo $o_nivel->getAleatorio()?"Sim":"Não" ?>
					</td>
					<td>
						<?php echo $o_nivel->getTotalQuestoes()?>
					</td>
			
					<td align="center">
						<a href='?controle=Nivel&acao=manterNivel&in_id=<?php echo $o_nivel->getId()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=Nivel&acao=apagarNivel&in_id=<?php echo $o_nivel->getId()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
		<a href='?controle=Nivel&acao=manterNivel' class='bt_green'>Novo Nivel</a>
	</div>
</body>
</html>