<!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Língua Brasileira de Sinais (LIBRAS)</h1>
        <hr>
        <p>A Língua Brasileira de Sinais – LIBRAS – é a língua utilizada pelos surdos brasileiros e é uma língua de sinais que, como as usadas em diferentes países, apresenta regras que respondem pela formação dos sinais e pela organização destes nas estruturas frasais e no discurso.</p>
        
        <p>Diferentemente das línguas orais, os principais articuladores das línguas de sinais são as mãos, que se movimentam principalmente no espaço em frente ao corpo e articulam sinais em determinadas localizações nesse espaço. Kyle e Woll apontam algumas propriedades exclusivas das línguas de sinais (KYLE; WOLL; PULLEN, 1988), tais como o uso de gestos simultâneos, o uso do espaço e a organização e ordem que daí resultam. Assim, as línguas de sinais possuem uma modalidade de produção motora (mãos, face e corpo) e uma modalidade de percepção visual.</p>

        <p>Embora existam aspectos universais, pelos quais se regem todas as línguas de sinais, a comunicação gestual dos Surdos não é universal. As línguas de sinais, assim como as orais, pertencem às comunidades onde são usadas, tendo apresentando diferenças con- sideráveis entre as determinadas línguas (WIKIPEDIA, 2013). Para os brasileiros com deficiência auditiva, a LIBRAS é sua língua principal e o português escrito a língua se- cundária, sendo que se percebe uma dificuldade de grande parte da comunidade surda no aprendizado do português. Essa dificuldade deve-se, dentre outros, à falta de sentido￼do raciocínio com base em fonemas como nós, ouvintes, fazemos, associando o fonema ao grafema; associação esta totalmente arbitrária ao surdo sinalizador (JANUÁRIO; LEITE; KOGA, 2010).</p>

        <p>De acordo com dados do IBGE de 2010, existem no Brasil cerca de 10 milhões de surdos, dentre os quais 2 milhões não conhecem a língua portuguesa (CHIHAYA, 2012). E este tipo de dificuldade vivida por milhões de brasileiros é a motivação para a criação de ferramentas que auxiliem os surdos no aprendizado e na associação com textos escritos em português.</p>

        <p>Além disso, há também a necessidade de que ouvintes aprendam a língua de sinais, principalmente educadores que devem garantir o cumprimento do Decreto Federal 5626, de 22 de dezembro de 2005 (Presidência da República, 2005), que estabelece que os alunos surdos devem ter uma educação bilíngue, na qual a Língua Brasileira de Sinais é a primeira e a Língua Portuguesa, na modalidade escrita, a segunda. Quanto mais pessoas dominarem a Língua Brasileira de Sinais, mais estaremos próximos de uma sociedade igualitária, superando as barreiras de comunicação enfrentadas entre deficientes auditivos e não deficientes (JANUÁRIO; LEITE; KOGA, 2010).</p>

        <h2> Referências Bibliográficas</h2>

        <p>BEDIKIAN, R. Understanding Latency. 2013. Disponível <a href="http://labs.leapmotion.com/post/55354675113/understanding-latency-part-1">aqui</a>.</p>
        
        <p>CHIHAYA, K. Deficiência auditiva atinge 9,7 milhões de brasileiros. 2012. Disponível <a href="http://www.winaudio.com.br/produtos-e-servicos/noticias-em-audiologia/3704- deficiencia-auditiva-atinge-98-milhoes-de-brasileiros.html">aqui</a>.</p>

        <p>EL-LAITHY, R.; HUANG, J.; YEH, M. Study on the use of microsoft kinect for robotics applications. In: Position Location and Navigation Symposium (PLANS), 2012 IEEE/ION. [S.l.: s.n.], 2012. p. 1280–1288. ISSN 2153-358X.</p>

        <p>HARDENBERG, C. von; BÉRARD, F. Bare-hand human-computer interaction. In: Proceedings of the 2001 workshop on Perceptive user interfaces. New York, NY, USA: ACM, 2001. (PUI ’01), p. 1–8. Disponível <a href="http://doi.acm.org/10.1145/971478- .971513">aqui</a>.</p>

        <p>JANUÁRIO, G. C.; LEITE, L. A. F.; KOGA, M. L.
        <br>POLI-LIBRAS - Um Tradutor de Português para LIBRAS — Escola Politécnica da Universidade de São Paulo, São Paulo, 2010.</br>

        <p>KYLE, J.; WOLL, B.; PULLEN, G. Sign Language: The Study of Deaf People and Their Language. Cambridge University Press, 1988. ISBN 9780521357173. Disponível <a href="http://books.google.com.br/books?id=Gcy4MhmLhdkC">aqui</a>.</p>

        <p>Presidência da República. Decreto No 5.626. 2005. Disponível <a href="http://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/decreto/d5626.htm">aqui</a>.</p>

        <p>WEICHERT, F. et al. Analysis of the accuracy and robustness of the leap motion controller. Sensors, 2013. v. 13, n. 5, p. 6380–6393, 2013. ISSN 1424-8220. Disponível <a href="http://www.mdpi.com/1424-8220/13/5/6380">aqui</a>.</p>

        <p>WIKIPEDIA. Língua de Sinais. 2013. Disponível <a href="http://pt.wikipedia.org/wiki/Língua de sinais">aqui</a>.</p>

      </div>