      <div class="row">
        <div class="span4">
          <img src="template/images/" class="img-polaroid" style="width: 200px; height: 300px">
          <h2>Diogo Borges Krobath</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p class="text-right"><a class="btn" href="http://www.linkedin.com/pub/diogo-borges-krobath/9/751/315"><img src="template/images/linkedin-icon.png" class="img-circle" style="width: 50px; height: 50px"></a></p>
        </div>
        <div class="span4">
          <img src="template/images/ken.jpg" class="img-polaroid" style="width: 200px; height: 300px">
          <h2>Kenji Sakata Jr.</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p class="text-right"><a class="btn" href="http://www.linkedin.com/pub/kenji-sakata-jr/27/1a9/a5a"><img src="template/images/linkedin-icon.png" class="img-circle" style="width: 50px; height: 50px"></a></p>
       </div>
        <div class="span4">
          <img src="template/images/" class="img-polaroid" style="width: 200px; height: 300px">
          <h2>Victor Lassance</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p class="text-right"><a class="btn" href="http://www.linkedin.com/pub/victor-lassance-oliveira-e-silva/41/32/348"><img src="template/images/linkedin-icon.png" class="img-circle" style="width: 50px; height: 50px"></a></p>
        </div>
      </div>