<!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Leap-LIBRAS</h1><hr>
        <div class="row-fluid">
          <div class="span6 offset3">
            <img src="template/images/leap-motion-libras.jpg" class="img-polaroid">
          </div>
        </div>
        <br>
        <h2>Missão</h2>
        <p>Permitir aos deficientes auditivos de superar barreiras de comunicação</p>
        <h2>Mas, afinal, o que é Leap-LIBRAS?</h2>
        <p>Leap-LIBRAS é um jogo que dá suporte para o aprendizado de LIBRAS de forma lúdica e interativa, cuja abrangência é voltada para qualquer público, entre os quais adultos e crianças, deficientes auditivos ou não, alfabetizados ou não.</p>
        <p>A motivação para sua criação advém do fato de que apenas uma parcela reduzida da população sabe se comunicar através de LIBRAS e da importância disso para a inclusão social de deficientes auditivos.</p>
        <p>O formato encontrado para atingir esses objetivos é através de um jogo, no qual além de propiciar o aprendizado de LIBRAS, atinge-se as redes sociais dos usuários e divulga-se o seu progresso e conquistas ao longo dele.</p>
        <h2>Qual é o diferencial?</h2>
        <p>O grande diferencial do Leap-LIBRAS é a capacidade de compreender os gestos em LIBRAS dos usuários sem a necessidade que estes portem fisicamente qualquer tipo de aparelho. Isso graças ao uso da tecnologia de ponta ©Leap Motion.
      </div>