      <div class="row">
        <div class="span4">
          <img src="template/images/diogo.jpg" class="img-polaroid" style="height: 200px">
          <h2>Diogo Borges Krobath</h2>
          
          <hr>
          
          <h3>Eng. de Computação</h3>
          <ul>
            <li><strong>2007-2013:</strong> Escola Politécnica da Universidade de São Paulo</li>
            <li><strong>2010-2012:</strong> Politecnico di Milano (Itália)</li>
          </ul>

          <h3>Áreas de Interesse</h3>
          <ul>
            <li>Storage</li>
            <li>SAN</li>
            <li>Data Migration</li>
            <li>Knowledge Management</li>      
          </ul>

          <p class="text-right"><a class="btn" href="http://www.linkedin.com/pub/diogo-borges-krobath/9/751/315"><img src="template/images/linkedin-icon.png" class="img-circle" style="width: 50px; height: 50px"></a></p>
        </div>
        <div class="span4">
          <img src="template/images/ken.jpg" class="img-polaroid" style="height: 200px">
          <h2>Kenji Sakata Jr.</h2>
          
          <hr>

          <h3>Eng. de Computação</h3>
          <ul>
            <li><strong>2008-2013:</strong> Escola Politécnica da Universidade de São Paulo</li>
            <li><strong>2011-2013:</strong> Université de Technologie de Compiègne (França)</li>
          </ul>

          <h3>Áreas de Interesse</h3>
          <ul>
            <li>Storage</li>
            <li>SAN</li>
            <li>Data Migration</li>
            <li>Knowledge Management</li>      
          </ul>

          <p class="text-right"><a class="btn" href="http://www.linkedin.com/pub/kenji-sakata-jr/27/1a9/a5a"><img src="template/images/linkedin-icon.png" class="img-circle" style="width: 50px; height: 50px"></a></p>
       </div>
        <div class="span4">
          <img src="template/images/victor.jpg" class="img-polaroid" style="height: 200px">
          <h2>Victor Lassance</h2>
          
          <hr>
          
          <h3>Eng. de Computação</h3>
          <ul>
            <li><strong>2008-2013:</strong> Escola Politécnica da Universidade de São Paulo</li>
            <li><strong>2010-2012:</strong> École Centrale de Lyon (França)</li>
          </ul>

          <h3>Áreas de Interesse</h3>
          <ul>
            <li>Software Engineering</li>
            <li>VBA</li>
            <li>C</li>
            <li>Java</li>      
          </ul>

          <p class="text-right"><a class="btn" href="http://www.linkedin.com/pub/victor-lassance-oliveira-e-silva/41/32/348"><img src="template/images/linkedin-icon.png" class="img-circle" style="width: 50px; height: 50px"></a></p>
        </div>
      </div>