<!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Explicação do Jogo</h1>
        <hr>
        <p>Antes de tudo, verfique que seu <strong>LeapMotion©</strong> está conectado ao seu computador. </p>
        <p>Para começar a jogar, selecione a opção <strong>Jogar</strong> do menu superior. Em seguida, selecione o nível que deseja jogar. </p>

        <div class="row-fluid">
          <div class="span6 offset3">
            <img src="template/images/leap_libras.png" class="img-polaroid">
          </div>
        </div>

      </br>

        <p>O jogo possui três níveis de dificuldade. Só se torna possível escolher os níveis 2 e 3 caso você já tenha atingido a meta do nível anterior.</p>

        <h3>Nível 1: Básico</h3>

        <p>Faça o gesto em LIBRAS perguntado na <strong>Questão</strong>. Antes de começar, veja como fazer o gesto, cliacando no botão <strong>Aprenda o gesto</strong>. </p>
        <p>Se você acertar, ganha um ponto. Clique no botão <strong>Próximo gesto</strong> para continuar jogando. Quando você acumular pontos o suficiente para passar para o próximo nível, você será redirecionado automaticamente ao próximo nível.</p>

        <p> Você pode voltar a jogar o <strong>Nível 1</strong> sempre que quiser.</p>
      
        <h3>Nível 2: Intermediário</h3>

        <p>Nesta fase as regras são as mesmas, mas os gestos são mais difíceis</p>

        <p>E aí, topa o desafio?</p>

        <h3>Nível 3: Avançado</h3>
        
        <p>Até aqui foi tudo muito fácil! Vamos ver se você aprendeu de verdade?</p>

        <p>O objetivo é fazer você fixar os gestos aprendidos no <strong>Nível 1 e Nível 2</strong>. </p>

        <p>Bom, para fazer isso, você deverá reproduzir os mesmos gestos das fases anteriores, mas  agora não terá mais ajuda do botão <strong>Aprenda o gesto</strong>.</p>

        <p>Sempre estamos trabalhando com os mesmos gestos, mas agora, além de não ter mais ajuda do <strong>Aprenda o gesto</strong>, os gestos agora poderão aparecer numa ordem qualquer.</p>
       

      </div>