<!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h2><img src="template/images/minerva.jpg" class="img-polaroid" style="width: 150px; height: 150px"> Escola Politécninca da Universidade de São Paulo</h2>
        <hr>
        <h1>PCS2057 - Multimídia e Hipermídia</h1>
        <h2>Objetivos</h2>
        <ul>
          <li>Apresentar as tecnologias básicas necessárias ao desenvolvimento de sistemas de multimídia/hipermídia e realidade virtual;</li>
          <li>Analisar as diversas áreas de aplicações, bem como técnicas, metodologias e ferramentas de desenvolvimento;</li>
          <li>Discutir o estado da arte, perspectivas de evolução, e desafios a serem vencidos; propiciar o contato prático com os aspectos relacionados à criação e produção de sistemas interativos avançados.</li>
        </ul>
        <h2>Docentes Responsáveis</h2>
        <ul>
          <li>Prof. Dr. Romero Tori</li>
          <li>Profa. Dra. Regina Melo Silveira</li>
        </ul>

        <h2>Programa Resumido</h2>
        <ul>
          <li>Caracterização das tecnologias de Hipertexto, Hipermídia, Multimídia e Realidade Virtual.</li> 
          <li>Histórico e evolução do Hipertexto e da Hipermídia. Conceitos de Comunicação e mídia.</li> 
          <li>Interface de navegação em espaços informacionais. Estruturas de navegação e métricas.</li>
          <li>Tipos de dados de multimídia. Modelos e padrões. Animações. Vídeo Digital. Som digital.</li> 
          <li>Formatos de Mídia e Compressão. Hardware e software básicos de tecnologias interativas.</li>
          <li>Infra-estrutura de comunicação. Considerações sobre o projeto de sistemas multimídia interativos.</li> <li>Problemas a serem resolvidos.</li>
        </ul>

        <h2>Projeto</h2>
        <p>No contexto da disciplina PCS 2057, o grupo deve desenvolver um projeto que é desenvolvido segundo as seguintes etapas:</p>
        <ul>
          <li>Prospecção</li> 
          <li>Estudo das tecnologias envolvidas</li> 
          <li>Levantamento de trabalhos relacionados</li>
          <li>Elaboração da Proposta</li> 
          <li>Desenvolvimento do Projeto</li>
          <li>Prova de Conceito</li>
          <li>Avaliação Contínua</li>
        </ul>
        <p>As aplicações resultantes do desenvolvimento do projeto pressupõem a utilização de dados, ádio e vídeo de forma simultânea e integrada, visando facilitar e tornar mais eficiente a interação humano-computador.</p>
        <p>Há diversos domínios de aplicação que podem ser considerados pelo projeto como IPTV, telework, e-­health, e‐banking, e‐learning, videoconferência, realidade virtual, realidade aumentada, VoIP, games, sistemas de comunicação, entre outros.</p>
        <p>Fomos orientados a utilizar novas tecnologias de forma a tornar o aprendizado mais desafiador e interessante. Tablets, smartphones, Leap Motion, MS Kinect, MS PixelSense, capacete de realidade virtual entre outras tecnologias foram sugeridas para serem utilizadas nesse projeto.</p>
        <p class="text-right"><a href="https://uspdigital.usp.br/jupiterweb/obterDisciplina?sgldis=PCS2057&verdis=2" class="btn btn-primary btn-large">Saiba Mais »</a></p>
      </div>