<?php
$v_params = $this->getParams();
$v_nivel_usuarios = $v_params['v_nivel_usuarios'];
?>
<div class="hero-unit">
    <h2>Lista com relações Usuário-Nível do jogo</h2>
    <hr>
	<div align="center">
		<table class='table table-striped'>
			<tr>
				<th>
					ID
				</th>
				<th>
					Usuário
				</th>
				<th>
					Nível
				</th>
				<th>
					Max Score
				</th>
				<th colspan="2">
					Ações
				</th>
			</tr>
			<?php
			foreach($v_nivel_usuarios AS $o_nivel_usuario)
			{
				?>
				<tr>
					<td>
						<?php echo $o_nivel_usuario->getId() ?>
					</td>
					<?php if ($o_nivel_usuario->getUsuario()->getId()) { ?>
						<td title="<?php echo $o_nivel_usuario->getUsuario()->getEmail() ?>">
							<?php echo $o_nivel_usuario->getUsuario()->getNome() . " (" .
										$o_nivel_usuario->getUsuario()->getNivelAcesso()->getNome() . ")"; ?>
						</td>
					<?php } else { ?>
						<td>
							<?php echo "ID " . $o_nivel_usuario->getIdUsuario() . " (deletar)"; ?>
						</td>
					<?php } ?>
					<td title="Level: <?php echo $o_nivel_usuario->getNivel()->getLevel() ?>">
						<?php echo $o_nivel_usuario->getNivel()->getNome() ?>
					</td>
					<td>
						<?php echo $o_nivel_usuario->getMaxScore()?>
					</td>
			
					<td align="center">
						<a href='?controle=NivelUsuario&acao=manterNivelUsuario&in_id=<?php echo $o_nivel_usuario->getId()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=NivelUsuario&acao=apagarNivelUsuario&in_id=<?php echo $o_nivel_usuario->getId()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
		<a href='?controle=Tabela&acao=listarTabela'><i class="icon-circle-arrow-left"></i> Voltar à Lista de Tabelas</a>
		|
		<a href='?controle=NivelUsuario&acao=manterNivelUsuario'><i class="icon-plus-sign"></i> Nova relação Usuário-Nível</a>
	</div>
</div>