<!-- Main hero unit for a primary marketing message or call to action -->
<?php
  $v_params = $this->getParams();

  $nome_gesto = $v_params['nome_gesto'];
  $titulo_level = $v_params['titulo_level'];
  $mostra_ajuda = $v_params['mostra_ajuda'];
  $url_midia = $v_params['url_midia'];
  $tipo_midia = $v_params['tipo_midia'];
  $pontuacao = $v_params['pontuacao'];
  $max_pontuacao = $v_params['max_pontuacao'];
  $json_gesto = $v_params['json_gesto'];
  $level = $v_params['level'];
  $questao = $v_params['questao'];

  $imagemUrl = "upload/";
?>
	  <div class="hero-unit">
        <h1><?php echo $titulo_level;?></h1>
        <h2>Questão: Faça o gesto <?php echo $nome_gesto;?></h2>
        
        <hr>

        
          <div class="row-fluid">
            <?php if($mostra_ajuda == true){?>
            <div class="span4 text-left">
              
              <!-- Button to trigger modal -->
              <a href="#modalVideo" role="button" class="btn btn-primary btn-large" data-toggle="modal">Aprenda o gesto <i class="icon-facetime-video icon-white"></i></a>
              <!-- Modal -->
              <div id="modalVideo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalVideoLabel" aria-hidden="true">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                  <h3 id="modalVideoLabel">Aprenda o gesto <?php echo "$nome_gesto com "; if($tipo_midia =='V') echo "o vídeo."; else echo "a imagem." ?> </h3>
                </div>
                <div class="modal-body">
                  <?php 
                    if($tipo_midia =='V') 
                      echo "<iframe width='520' height='315' src='$url_midia' frameborder='0' allowfullscreen></iframe>";
                    else{ ?>
                      <div class="row-fluid">
                        <div class="span6 offset3">
                          <?php echo "<img src='$imagemUrl$url_midia' class='img-polaroid'>"; ?>
                        </div>
                      </div>   
                  <?php } ?>
                </div>
                <div class="modal-footer">
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
                </div>
              </div>
            </div>
            <?php } else{ ?>
              <div class="span4 text-left">
                <a href="#modalVideo" role="button" class="btn btn-primary btn-large disabled" data-toggle="modal">Aprenda o gesto <i class="icon-facetime-video icon-white"></i></a>
              </div>
            <?php } ?>


            <div class="span4 text-center">
              <p class="btn-info" id="mensagem_usuario">Pontuação: <?php echo $pontuacao; ?>% <br />MAX SCORE: <?php echo $max_pontuacao; ?>%</p>
            </div>

            <div class="span4 text-right">
              <?php echo "<a href='?controle=Jogo&acao=listarJogo&level=$level&questao=$questao' class='btn btn-primary btn-large disabled' id='proximo_gesto'>Salvar pontuação e Avançar <i class='icon-forward icon-white'></i></a>"; ?>
            </div>

          </div>
          
          <hr>
		  <div id="main">
		  	<div id="render-area"></div>
		  </div>
		  <input type="hidden" id="gestoNome" value='<?php echo $nome_gesto; ?>' />
		  <input type="hidden" id="gestoJSON" value='<?php echo $json_gesto; ?>' />
      </div>

        