<?php
$v_params = $this->getParams();
$o_nivel = $v_params['o_nivel'];
$v_niveis = $v_params['v_niveis'];
?>
<div class="hero-unit">
    <h2>Nível do Jogo</h2>
    <hr>
	<form class="form-horizontal" method='post'>
	  <div class="control-group">
	    <label class="control-label" for="st_nome">Nome</label>
	    <div class="controls">
	      <input type="text" id="st_nome" name='st_nome' value='<?php echo $o_nivel->getNome()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_id_anterior">Nível Anterior</label>
	    <div class="controls">
  		  <select id="in_id_anterior" name='in_id_anterior'>
			  <option value=''> -- Nenhum -- </option>
  			  <?php foreach($v_niveis as $nivel) {
				  if ($o_nivel->getId() != $nivel->getId()) {
	  				  echo "<option value='{$nivel->getId()}' ";
	  				  if ($o_nivel->getIdAnterior() == $nivel->getId())
	  					  echo "selected";
	  				  echo ">{$nivel->getNome()}</option>";
				  }
  			  } ?>
  		  </select>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_id_proximo">Nível Seguinte</label>
	    <div class="controls">
		  <select id="in_id_proximo" name='in_id_proximo'>
			  <option value=''> -- Nenhum -- </option>
			  <?php foreach($v_niveis as $nivel) {
				  if ($o_nivel->getId() != $nivel->getId()) {
					  echo "<option value='{$nivel->getId()}' ";
					  if ($o_nivel->getIdProximo() == $nivel->getId())
						  echo "selected";
					  echo ">{$nivel->getNome()}</option>";
				  }
			  } ?>
		  </select>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="st_level">Level</label>
	    <div class="controls">
	      <input type="text" id="st_level" name='st_level' value='<?php echo $o_nivel->getLevel()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="bo_aleatorio">Aleatório?</label>
	    <div class="controls">
		  <select id="bo_aleatorio" name='bo_aleatorio'>
		    <option value="false" <?php if (!$o_nivel->getAleatorio()) echo "selected" ?>>Não</option>
			<option value="true" <?php if ($o_nivel->getAleatorio()) echo "selected" ?>>Sim</option>
		  </select>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_total_questoes">Total Questões</label>
	    <div class="controls">
	      <input type="text" id="in_total_questoes" name='in_total_questoes' value='<?php echo $o_nivel->getTotalQuestoes()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_pct_aprovacao">Taxa de Aprovação (%)</label>
	    <div class="controls">
	      <input type="text" id="in_pct_aprovacao" name='in_pct_aprovacao' value='<?php echo $o_nivel->getPctAprovacao()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <div class="controls">
			<input type='hidden' name='controle' value='Nivel'>
			<input type='hidden' name='acao' value='manterNivel'>
			<input type='hidden' name='in_id' value='<?php echo $o_nivel->getId()?>'>
			<a href='?controle=Nivel&acao=listarNivel'>Cancelar</a>
			<button type='submit' class='btn'>Salvar</button>
	    </div>
	  </div>
	</form>
</div>