<?php
$v_params = $this->getParams();
$o_questao = $v_params['o_questao'];
$v_niveis = $v_params['v_niveis'];
$v_midia_gestos = $v_params['v_midia_gestos'];
?>
<div class="hero-unit">
    <h2>Questão do Jogo</h2>
    <hr>
	<form class="form-horizontal" method='post'>
	  <div class="control-group">
	    <label class="control-label" for="st_titulo">Título</label>
	    <div class="controls">
	      <input type="text" id="st_titulo" name='st_titulo' value='<?php echo $o_questao->getTitulo()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_id_nivel">Nível</label>
	    <div class="controls">
  		  <select id="in_id_nivel" name='in_id_nivel'>
  			  <?php foreach($v_niveis as $nivel) {
  				  echo "<option value='{$nivel->getId()}' ";
  				  if ($o_questao->getIdNivel() == $nivel->getId())
  					  echo "selected";
  				  echo ">{$nivel->getNome()}</option>";
  			  } ?>
  		  </select>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_id_midia_gesto">Mídia-Gesto</label>
	    <div class="controls">
		  <select id="in_id_midia_gesto" name='in_id_midia_gesto'>
			  <?php foreach($v_midia_gestos as $midia_gesto) {
				  echo "<option value='{$midia_gesto->getId()}' ";
				  if ($o_questao->getIdMidiaGesto() == $midia_gesto->getId())
					  echo "selected";
				  echo ">{$midia_gesto->getTitulo()}</option>";
			  } ?>
		  </select>
	    </div>
	  </div>
	  <div class="control-group">
	    <div class="controls">
			<input type='hidden' name='controle' value='Questao'>
			<input type='hidden' name='acao' value='manterQuestao'>
			<input type='hidden' name='in_id' value='<?php echo $o_questao->getId()?>'>
			<a href='?controle=Questao&acao=listarQuestao'>Cancelar</a>
			<button type='submit' class='btn'>Salvar</button>
	    </div>
	  </div>
	</form>
</div>