<?php
$v_params = $this->getParams();
$o_acesso = $v_params['o_acesso'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Acessos
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
	<div align="center">
		<form method='post'>
		<table class='table_list' width="300">
			<tr>
				<th>
					Nome
				</th>
				<th>
					Descrição
				</th>
				<th>
					Admin Gestos?
				</th>
				<th>
					Admin Acessos?
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<tr>
				<td>
					<input type='text' name='st_nome' value='<?php echo $o_acesso->getNome()?>'> 
				</td>
				<td>
					<input type='text' name='st_descricao' value='<?php echo $o_acesso->getDescricao()?>'>
				</td>		
				<td>
					<select name='bo_admin_gestos'>
					  <option value="false" <?php if (!$o_acesso->getAdminGestos()) echo "selected" ?>>Não</option>
					  <option value="true" <?php if ($o_acesso->getAdminGestos()) echo "selected" ?>>Sim</option>
					</select>
				</td>
				<td>
					<select name='bo_admin_acessos'>
					  <option value="false" <?php if (!$o_acesso->getAdminAcessos()) echo "selected" ?>>Não</option>
					  <option value="true" <?php if ($o_acesso->getAdminAcessos()) echo "selected" ?>>Sim</option>
					</select>
				</td>	
				<td align="center">
					<a href='?controle=Acesso&acao=listarAcesso' class='bt_red'>Cancelar</a>
				</td>
				<td align="center">
					<input type='hidden' name='controle' value='Acesso'>
					<input type='hidden' name='acao' value='manterAcesso'>
					<input type='hidden' name='in_id' value='<?php echo $o_acesso->getId()?>'>
					<button type='submit' class='bt_green'>Salvar</button>
				</td>
			</tr>			
		</table>
		</form>
	</div>
</body>
</html>