<?php
$v_params = $this->getParams();
$o_questao = $v_params['o_questao'];
?>
<div class="hero-unit">
    <h2>Questão do Jogo</h2>
    <hr>
	<form class="form-horizontal" method='post'>
	  <div class="control-group">
	    <label class="control-label" for="st_titulo">Título</label>
	    <div class="controls">
	      <input type="text" id="st_titulo" name='st_titulo' value='<?php echo $o_questao->getTitulo()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_id_nivel">ID Nível</label>
	    <div class="controls">
	      <input type="text" id="in_id_nivel" name='in_id_nivel' value='<?php echo $o_questao->getIdNivel()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <label class="control-label" for="in_id_midia_gesto">ID Mídia-Gesto</label>
	    <div class="controls">
	      <input type="text" id="in_id_midia_gesto" name='in_id_midia_gesto' value='<?php echo $o_questao->getIdMidiaGesto()?>'>
	    </div>
	  </div>
	  <div class="control-group">
	    <div class="controls">
			<input type='hidden' name='controle' value='Questao'>
			<input type='hidden' name='acao' value='manterQuestao'>
			<input type='hidden' name='in_id' value='<?php echo $o_questao->getId()?>'>
			<a href='?controle=Questao&acao=listarQuestao'>Cancelar</a>
			<button type='submit' class='btn'>Salvar</button>
	    </div>
	  </div>
	</form>
</div>