<?php
$v_params = $this->getParams();
$v_gestos = $v_params['v_gestos'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>
		Lista de gestos
	</title>
	<link rel="stylesheet" type="text/css" href="template/css/default.css" />
</head>
<body>
	<div align="center">
		<table class='table_list' width="80%">
			<tr>
				<th>
					ID
				</th>
				<th>
					Nome
				</th>
				<th>
					Json
				</th>
				<th colspan="2">
					A&ccedil;&otilde;es
				</th>
			</tr>
			<?php
			foreach($v_gestos AS $o_gesto)
			{
				?>
				<tr>
					<td>
						<?php echo $o_gesto->getId()?>
					</td>
					<td>
						<?php echo $o_gesto->getNome()?>
					</td>
					<td>
						<?php echo $o_gesto->getJson()?>
					</td>
			
					<td align="center">
						<a href='?controle=Gesto&acao=manterGesto&in_ges=<?php echo $o_gesto->getId()?>' class='bt_blue'>Editar</a>
					</td>
					<td align="center">
						<a href='?controle=Gesto&acao=apagarGesto&in_ges=<?php echo $o_gesto->getId()?>' class='bt_red'>Apagar</a>
					</td>
				</tr>
				<?php
			}
			?>
		</table>
		<br />
		<a href='?controle=Gesto&acao=manterGesto' class='bt_green'>Novo Gesto</a>
	</div>
</body>
</html>